---
- hosts: all
  become: yes
  vars:
    # ansible_python_interpreter: /usr/bin/python3.10
  environment:
    https_proxy: http://192.168.56.1:7890
    http_proxy: http://192.168.56.1:7890
    all_proxy: socks5://192.168.56.1:7890

  pre_tasks:
    - apt: update_cache=true cache_valid_time=3600

  tasks:

  - name: install dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - net-tools
      - libapr1-dev
      - libaprutil1-dev
      - libpcre2-dev


  # - name: Runtime Environment
  #   lineinfile:
  #     dest: "/etc/environment"
  #     regexp: "{{ item.regexp}}"
  #     line: "{{ item.line }}"
  #   with_items:
  #     - { regexp: '^LD_LIBRARY_PATH', line: 'LD_LIBRARY_PATH=/opt/openssl/lib64' }